# Generated by Django 4.1.3 on 2022-12-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://thumbs.dreamstime.com/z/delivery-line-icons-linear-set-quality-vector-such-as-envelope-door-supermarket-side-up-placeholder-food-boxes-qr-code-192543319.jpg', max_length=500),
        ),
    ]
